### PR TITLE
Make getInitialState optional (#2)

### PR DESCRIPTION
**Pull request by rstacruz**
See #2.

### CODE REVIEW

**Comment by nrn** [comment]
Thanks for the PR! I've been thinking about not requiring getInitialState for some slightly different use-cases, so this puts me over the edge.

**Comment by nrn** [comment]
Published with 1.1.0

**Comment by rstacruz** [comment]
> so this puts me over the edge.

in a good way i hope!

**Comment by nrn** [comment]
Totally :)

**Pull request merged**
